### ISSUE TITLE
separate share for CTM

### ISSUE THREAD

**Issue by gubuntu** [kartoza/maps.kartoza.com#16]
split CTM web map folder out of maps.kartoza.com folder structure so it syncs to maps.kartoza.com with its own Resilio share.

**Comment by NyakudyaA** [comment]
All done and web map now uses this folder

![sync](https://user-images.githubusercontent.com/2510900/58326718-f6c14480-7e2d-11e9-92d3-279cb3bc4757.png)

**Comment by gubuntu** [comment]
In my Resilio I see this peer for my CapeTownMarathonGIS folder: prod-ctm-data.kartoza.com -  can you confirm this is the instance running on maps.kartoza.com

**Comment by NyakudyaA** [comment]
> In my Resilio I see this peer for my CapeTownMarathonGIS folder: prod-ctm-data.kartoza.com - can you confirm this is the instance running on maps.kartoza.com

Yes that is the instance running on maps.kartoza.com. If you look at the maps.kartoza.com share I have deleted the CTM there
