### ISSUE TITLE
Upgrade web map project to use QGIS 3.4

### ISSUE THREAD

**Issue by gubuntu** [kartoza/maps.kartoza.com#17]
Upgrade web map project to use QGIS 3.4 and communicate with Chris, make sure it's syncing

**Comment by NyakudyaA** [comment]
Upgraded this and it is syncing between the website.

![ctm](https://user-images.githubusercontent.com/2510900/58631226-2a92e300-82e2-11e9-9c52-b39d62a82e40.png)

**Comment by gubuntu** [comment]
Check that Chris can open the new project and edit styles successfully
