### ISSUE TITLE
Add SSL to maps.kartoza.com

### ISSUE THREAD

**Issue by gubuntu** [kartoza/maps.kartoza.com#2]
_From @gubuntu on November 20, 2017 8:53_

_Copied from original issue: kartoza/kartoza#446_

**Comment by ann26** [comment]
SSL is added

**Comment by gubuntu** [comment]
SSL is no longer in place, @ann26 and @NyakudyaA please fix

**Comment by NyakudyaA** [comment]
@ann26  another gentle reminder again. Make sure SSL does not break load balancer. There are people who have  done that - combining load balancer and SSL i.e https://medium.com/@AaronThorp/rancher-load-balancing-multiple-domains-and-ssl-ec0d2d81a0f3

**Comment by NyakudyaA** [comment]
This has been fixed now. I have to do a PR with the latest docker-compose for maps.kartoza.com then we can close this issue
