### ISSUE TITLE
Add new base map layer to CTM

### ISSUE THREAD

**Issue by gubuntu** [kartoza/maps.kartoza.com#3]
_From @gubuntu on October 31, 2017 11:41_

This link from the CT open data portal is for a WMTS of 8cm 2017 imagery.

It needs to be added as another basemap option

https://citymaps.capetown.gov.za/agsext1/rest/services/Aerial_Photography_Cached/AP_2017_Jan/MapServer/WMTS/1.0.0/WMTSCapabilities.xml

_Copied from original issue: kartoza/kartoza#445_

**Comment by NyakudyaA** [comment]
Added
![aerial](https://user-images.githubusercontent.com/2510900/42640632-06033a7c-85f3-11e8-9faf-ed1d4c0f32e8.png)

**Comment by gubuntu** [comment]
Thanks - but it appears to be drawing over the other layers with compositing?

Also please rename Othophoto layers to 'NGI Orthophoto' and 'CT Orthophoto'

**Comment by gubuntu** [comment]
done
