### ISSUE TITLE
Deploy Topostyle project on maps.kartoza.com

### ISSUE THREAD

**Issue by gubuntu** [kartoza/maps.kartoza.com#5]
_From @gubuntu on August 25, 2014 7:41_

The objective here is to deploy the Afrispatial styles 'live' in a QGIS server project and publish in the maps.kartoza.com gallery.  
- figure out from Tim where and how to deploy the following
  *\* set up maps.kartoza.com btsync
  *\* repo clone 
  *\* restore NGI db dump from a working instance (1Map?)
  *\* deploy QGIS project using topostyle QGIS styles

Adapt the project slightly so that provincial boundaries are visible at all scales and default zoom is 1:50000 on some random  place in SA each time the page is opened. 

_Copied from original issue: kartoza/kartoza#89_

**Comment by NyakudyaA** [comment]
The map has been deployed on maps.kartoza.com. Continous improvement will be done when there is time. Had a chat with the guys at NGI on how they do them. Besides map cartography, they also shift the labels manually, have graphic designers that look at each block etc to make them look nice.

**Comment by NyakudyaA** [comment]
Added a search control icon for someone to zoom into a specific town or place. Also, have an OSM overview map showing your relative location

**Comment by NyakudyaA** [comment]
The search is using OSMGeocoder. I have tried to search Hilton as well and it doesn't bring anything but Hilton South Africa. I will investigate the zoom levels changing when you search

**Comment by gubuntu** [comment]
Hilton still took me direct to somewhere in another country. 

Show a list of results to let a user choose where to go (and filter for results in SA only)

**Comment by NyakudyaA** [comment]
Still, haven't implemented the search to be restricted to South Africa only. Still on my to do list

**Comment by Vries14** [comment]
I have added the home button and restricted searches to be only in south africa
![tooltip_004](https://user-images.githubusercontent.com/42169058/49014723-bd16c600-f189-11e8-8293-77af7ca8f4eb.png)

**Comment by gubuntu** [comment]
nice @Vries14, it's working well

**Comment by NyakudyaA** [comment]
@gubuntu can you give me permission on this repo so that I can close issues that have been resolved like this one

**Comment by gubuntu** [comment]
OK @NyakudyaA try again

**Comment by NyakudyaA** [comment]
Thanks. Closing this issue
