### ISSUE TITLE
selectively render classes in GetLegendGraphic

### ISSUE THREAD

**Issue by gubuntu** [kartoza/maps.kartoza.com#9]
See the 5km marker legend in the latest version of the webmap. I added another rule-based class for scale dependency — how do we get the legend to show just the class that is being used at a particular scale and not other classes?

**Comment by NyakudyaA** [comment]
I have looked at the various solutions on this and it is working now.
![markers](https://user-images.githubusercontent.com/2510900/42572338-afda6dac-8519-11e8-9c05-d03b3b0bb53a.png)
Solution to this.
* Add an alternate style to the layer that only has one class.
* Implement a getLegend request with an alternate style.
* Layers are still being rendered by the default style that has all the rules

**Comment by gubuntu** [comment]
Now that's clever! Well done @NyakudyaA !
